version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Asilzhan7
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    environment:
      - DB_DSN=postgres://postgres:Asilzhan7@postgres:5432/postgres?sslmode=disable
